### ISSUE TITLE
Decoding odds data

### ISSUE THREAD

**Issue by HMaker** [S1M0N38/soccerapi#11]
I see this library does not uses selenium or other browser automation tools to scrape data from bet365, it is interesting. Is it being maintained?

**Comment by S1M0N38** [comment]
At the moment is not maintained (due to time constraints), but maybe in the future I will fix the bugs that appears.  

At the time when I was developing ...
The code just perform an http request to bet365 which responds with a file full of data that in order to understand had to decoded. The a [silly function](https://github.com/S1M0N38/soccerapi/blob/4a1c45c7c76a935a3c03b9c099619043fd3ac1e4/soccerapi/api/bet365/bet365.py#L25) try to guess the key for the _xor_ process and then, when the key was found, it is used to make odds data readable.

Nowadays bet365 maybe have changed something and the whole code is now broke.

**Comment by HMaker** [comment]
@S1M0N38 Could you document how to deobuscate bet365 data? I see they keep two websocket connections open to update the site's data, it seems that websocket messages are obfuscated. I found that bet365 employs mechanisms to block automation bots, in that cases people most of time uses Selenium or other browser automation tools. Is it hard to deobuscate their data?

**Comment by S1M0N38** [comment]
I investigate the bug and turn out to be just a minor change in a ["parsing keyword"](https://github.com/S1M0N38/soccerapi/commit/f5d2d2f94f86c43c1da4a4886dbad57b4b2a66d1). I also update some of the leagues ids (france-league_1 and italy-serie_b) and only when competitions start again I can update all leagues ids. Remember that bet365 (maybe) work if requests are perform from Italy (other country are not tested and VPN are detected by bet365).

**Comment by HMaker** [comment]
Following the request's stacktrace in chrome's debugger I found the JS code that decodes the odd's values:
```
function e(t, e) {
    var n, r, s, a;
    if (!t || !e)
        return t;
    for (e != i && (C = {}, i = e), r = e.charCodeAt(0), s = "", a = 0; a < t.length; a++)
        s += String.fromCharCode(t.charCodeAt(a) ^ r);
    return s
}
```
Do you know from where the key `e` comes from?

**Comment by HMaker** [comment]
@S1M0N38 Also, your brute force algorithm scans from 0 to 130, but `String.charCodeAt()` and `String.fromCharCode` works with UTF-16 chars which goes from 0 to 65535 (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt). Am I missing something?

**Comment by S1M0N38** [comment]
Yes, my approach it's quite heuristic. I don't know where the key come from (but my suspect is that can be found in js client side with a further effort). When I was developing I send a bunch of request and I saw that the key char was always in range from 0 to 130. At  the moment (12th ago 2020) api/bet365.py shoud works just for _france - ligue_1_ (the only available main competition on bet365, I plan to update the .json file where other competition appear on the site). Remember that i ran my test from Italy and performing request from other country was not tested. 

If try to make it work you can set up the following the env (I use pipenv for deps manager) 

1. clone the repo: `git clone git@github.com:S1M0N38/soccerapi.git`
2. go into repo: `cd soccerapi`
3. install dependencies (for developing): `pip install -e . && pipenv install --dev `
4. activate pipenv `pipenv shell` and start to play around

For test running _pytest_ is used. To run all test use `pytest`. For test option read pytest docs

**Comment by HMaker** [comment]
I tested from other countries, the xor key search works. I will try to find where the xor key is generated. From what I saw so far they build a kind of tree from that raw data that is returned by `/SportsBook.API/web?`, each node is called "stem" and has a corresponding UI element that display its content, that stem is the UI state I think. The odds' stem has a special attribute called `_T` that is the xor key, it is introduced somewhere since that `_T` parameter does not comes in the raw data. Search for `this.stem.data._T` and  `stemUpdateHandler` in the JS code to analyze it if you want. At last in Chrome the global search does not work, I think that's because bet365 load all the JS dynamically, but you can follow the request's stacktrace and search in each file.

**Comment by HMaker** [comment]
I think this issue is solved now
