### ISSUE TITLE
Data missplaced on bet365 API

### ISSUE THREAD

**Issue by verdenkaf** [S1M0N38/soccerapi#18]
Hey Simon, great work on that script!

Unibet and 888Sport works fine, but bet365 gets the data in a order that shouldn't happen. 

If you get the bet365 odds it gets messed in the full_time_result getting the data for next events instead the actual draw and away odds, you can take a look in the german bundesliga 2 e.g.:

![image](https://user-images.githubusercontent.com/9340416/96533835-fc120100-1264-11eb-91d1-417276bd8280.png)

You can see that in the "Hamburg v Aue" event. The odds in the draw and away_team fields are actually the odds for Jahn Regensburg and Nurnberg.

Is that a known problem with bet365 data? 

Thanks!

**Comment by nejcb1** [comment]
Yeah, this is a bug.
