### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by filetopaixao** [S1M0N38/soccerapi#32]
I would like to extract data from matches such as: corners, dangers attack, possession of the ball, shots on goal ...

I can make the request for the following link:
https://www.bet365.it/SportsBook.API/web?lid=33&zid=0&pd=%23AC%23B1%23C1%23D8%23E98559178%23F3%23P%5E13%23Q%5E0%23&cid=28&ctid=28

But I can't identify this data in it, could someone help me?

**Comment by xhantos** [comment]
If you have the right headers and so the response you get it's correct, you got to deobfuscate the odds. You can check our solution to your issue in `_parse_odds()` method in [bet365.py](https://github.com/S1M0N38/soccerapi/blob/master/soccerapi/api/bet365.py)
